import type { Metadata } from "next";
import { alliance2 } from "@/app/fonts";
import "./globals.css";
import Navbar from "@/app/Components/navigation/Navbar"
import Footer from "./Components/UI/Footer";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body
    className={`${alliance2.className} antialiased flex w-full min-h-full flex-col bg-[--root-bg]`}
    >
        <header id="header">
          <Navbar />
        </header>
        <main className="relative w-full m-auto edge-to-edge-container">{children}</main>
        <Footer email="rahulsingh.uxd@gmail.com" phone="+91-6291233251" />
      </body>
    </html>
  );
}
