import type { Metadata } from "next";
import {alliance2} from '@/app/ui/fonts';
import "./globals.css";
import Navbar from "./ui/layout";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body className={alliance2.className}>{children}</body> */}
      <body className= {` ${alliance2.className} antialiased max-w-7xl mx-4 mt-8 lg:mx-auto`}>
        <Navbar />
        <main className="flex-auto min-w-0 w-full mt-6 flex flex-col px-2 md:px-0">
        {children}
        </main>
      </body>
    </html>

  );
}
